### ISSUE TITLE
Running test error

### ISSUE THREAD

**Issue by americool** [americool/vndr_ideas#18]
ENOENT: no such file or directory, stat '/Users/abe/Desktop/VNDR/vndr/node_modules/react-native/Libraries/Renderer/src/renderers/shared/stack/event/EventPluginRegistry.js'
        at Error (native)
      
![screen shot 2017-01-05 at 8 09 14 pm](https://cloud.githubusercontent.com/assets/16258690/21703841/06ac97a8-d383-11e6-9e0f-8264d213a54a.png)

**Comment by bdougie** [comment]
Which branch is this on? It looks like the the react-native module is missing something. Perhaps https://github.com/RealOrangeOne/react-native-mock

```sh
yarn add dev react-native-mock
```

Though I am not able to reproduce on my end, I get a passing test.
