### ISSUE TITLE
Refactor Needed

### ISSUE THREAD

**Issue by bdougie** [americool/vndr_ideas#21]
Looking through your code now - before merging to master give me a chance to review your code. 

This [bit of code](https://github.com/americool/vndr_ideas/blob/master/src/Vendors.js#L33-L41) needs to be in its own file and probably shouldn't be in the fetch. 

```js
const sortedData = data.sort((a, b) => {
  if (a.distance < b.distance) {
    return -1;
  }
  if (a.distance > b.distance) {
    return 1;
  }
  return 0;
 });
```

**Comment by americool** [comment]
I know. For whatever reason when I was writing that code as a separate function it wasn't working, I assume it was an issue with scope...I'll try to figure something out.
