### ISSUE TITLE
New Refactor Needed 

### ISSUE THREAD

**Issue by americool** [americool/vndr_ideas#27]
https://github.com/americool/vndr_ideas/blob/calc-distance/src/Form.js
https://github.com/americool/vndr_ideas/blob/calc-distance/src/helpers/calculateDistance.js

I'm currently working on the form section to allow a user to enter longitude and latitude of a vendor and have the program be able to compare said values against the user's location's long/lat and return an estimate of distance as the crow flies.  I've also added a helper function getDistance in another file which performs the calculations. However outside of that, almost all of the work is done in the following function: 

```javascript
submitNewVendor() {
    const {
      name,
      description,
      userLatitude,
      userLongitude,
    } = this.state;

    let {
      vendLatitude,
      vendLongitude
    } = this.state;

    vendLatitude = parseFloat(vendLatitude.trim());
    vendLongitude = parseFloat(vendLongitude.trim());
    const calcDistance =
    getDistance(userLatitude, userLongitude, vendLatitude, vendLongitude).toFixed(2);

    base.push('vendors', {
      data: {
        vndrName: name.trim(),
        description: description.trim(),
        distance: calcDistance }
    }).then(
      Actions.list()
    );
  }
```

While it currently works, it's pretty ugly and I think could use refactoring. I would purpose pulling all of the longitude and latitude related (user or vendor) state and variable modifications out of this code along with the helper function and putting them into their own method/function called setDistance. This function would end with the calcDistance constant used to set the state of distance. Then in the submitNewVendor function we could simply push the distance state into firebase along with name and description. I feel pretty confident doing this, however I'm less clear if we can simply call the second function within the first, or if that will cause issue of scope, or (my failed previous solution) if we can call two functions from the button's onPress feature here: 

```javascript
<CardSection>
          <Button onPress={this.submitNewVendor.bind(this)}> SUBMIT </Button>
</CardSection>
```

**Comment by bdougie** [comment]
Sorry to push back a bit on this, but can you rewrite the issue by answering the below questions. Provide code snippets or screen shots as well. This will ensure the reader (myself) can craft an answer that is relevant and useful.  

What is the Situation?

What is the Complication?

What are you trying to do?

What is a proposed solution?

**Comment by bdougie** [comment]
This still kind of hurts my brain when reading. Having knowledge of the project helps, but when writing an issue assume the reader has no idea what your app does. This will be useful when explaining in interviews or on teams in the future, its a learned skill. 

With that being said why `this.state` and not state inside a constructor [here](https://github.com/americool/vndr_ideas/blob/calc-distance/src/Form.js#L12-L22) compared to [here](https://github.com/americool/vndr_ideas/blob/calc-distance/src/Vendors.js#L15-L19)?

I would shy away from refactor for the sake of refactoring, if it works it works. Only refactor pain away, however ul to look at this function. Your function is named submitNewVendor but it is clearly doing other things prior to shipping off the new vendor to firebase. 
You could create 1 function and call it inside of the `submitNewVendor`. And even move it to the calcDistance.js helper, because it has nothing to do with the Form component.

```js
function calcDistance(vendLatitude, vendLongitude) {
    getDistance(
      userLatitude,
      parseFloat(userLongitude.trim()),
      parseFloat(vendLatitude.trim()),
      vendLongitude
    ).toFixed(2);
}
```

**Comment by americool** [comment]
Okay, I confess to being a little confused by all this. Certainly I can a few ways to approach this from your comments. I guess my two questions now are 1.) I still don't really understand the purpose of the constructor - so I guess we'll need to talk about that. 2.) In regards to issues in OS, is it really the  normal practice to explain the app in its entirety for every issue? I would assume if someone was working on it they would have some knowledge of it. Perhaps there's a good example of how issues/pr should be written that I can look at.

**Comment by bdougie** [comment]
1. We can chat about constructors, but take a read through the docs here https://facebook.github.io/react/docs/react-component.html#constructor. I was mainly curious if you were referencing somewhere else where a component state was created without the constructor. In short, the constructor gives you the ability to reload the component when the state is updated using `setState`. 

2. No, not necessary to explain your entire app every time an issue is open. I just want to stress providing context, I didn't quite get how the links at the beginning of the issue related to the issue. This could be solved with an inline link. My recommendation is to explore open issues on an open source project you are familiar with. Maybe start [here](https://github.com/airbnb/react-native-maps/issues/927)
